use std::path::Path;

fn main() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    for (filters, output, sys) in [
        (
            include_str!("../capture.txt"),
            "crates/gpui/src/platform/windows_screen_capture/bindings.rs",
            false,
        ),
        (
            include_str!("../wgpu.txt"),
            "crates/gpui_wgpu/src/wgpu_renderer/surfaces/windows/bindings.rs",
            false,
        ),
        (
            include_str!("../platform.txt"),
            "crates/gpui_windows/src/bindings.rs",
            false,
        ),
        (
            include_str!("../process.txt"),
            "crates/gpui_zed_util/src/windows_bindings.rs",
            true,
        ),
        (
            include_str!("../shaders.txt"),
            "crates/gpui_render/windows_bindings.rs",
            false,
        ),
    ] {
        let output = root.join(output);
        let mut args = vec!["--out", output.to_str().unwrap()];
        if sys {
            args.push("--sys");
        } else if output.ends_with("gpui_windows/src/bindings.rs") {
            args.extend([
                "--implement",
                "Windows.Win32.IDataObject",
                "Windows.Win32.IDataObjectAsyncCapability",
                "Windows.Win32.IDirectManipulationViewportEventHandler",
                "Windows.Win32.IDWritePixelSnapping",
                "Windows.Win32.IDWriteTextRenderer",
                "Windows.Win32.IDropTarget",
            ]);
        }
        args.push("--filter");
        args.extend(
            filters
                .lines()
                .map(str::trim)
                .filter(|line| !line.is_empty() && !line.starts_with("//")),
        );
        windows_bindgen::bindgen(args);
        let bindings = std::fs::read_to_string(&output).unwrap();
        std::fs::write(
            &output,
            format!(
                "// Generated by windows-bindgen 0.100.0.\n\
                 // Regenerate with `cargo run -p gpui_ce_windows_bindings`.\n\n\
                 #![allow(non_snake_case, non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]\n\n\
                 {bindings}"
            ),
        )
        .unwrap();
        println!("Generated {}", output.display());
    }
}
