// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub type BOOL = i32;
pub type PCWSTR = *const u16;
pub mod Windows {
    pub mod Win32 {
        pub mod Foundation {
            pub type HANDLE = *mut core::ffi::c_void;
            pub type NTSTATUS = i32;
            pub const STILL_ACTIVE: NTSTATUS = 0x103_u32 as _;
        }
        pub mod Security {
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct SECURITY_ATTRIBUTES {
                pub nLength: u32,
                pub lpSecurityDescriptor: *mut core::ffi::c_void,
                pub bInheritHandle: super::super::super::BOOL,
            }
            impl Default for SECURITY_ATTRIBUTES {
                fn default() -> Self {
                    unsafe { core::mem::zeroed() }
                }
            }
        }
        pub mod System {
            pub mod JobObjects {
                windows_link::link!("kernel32.dll" "system" fn AssignProcessToJobObject(hjob : super::super::Foundation:: HANDLE, hprocess : super::super::Foundation:: HANDLE) -> super::super::super::super::BOOL);
                windows_link::link!("kernel32.dll" "system" fn CreateJobObjectW(lpjobattributes : *const super::super::Security:: SECURITY_ATTRIBUTES, lpname : super::super::super::super::PCWSTR) -> super::super::Foundation:: HANDLE);
                windows_link::link!("kernel32.dll" "system" fn SetInformationJobObject(hjob : super::super::Foundation:: HANDLE, jobobjectinformationclass : JOBOBJECTINFOCLASS, lpjobobjectinformation : *const core::ffi::c_void, cbjobobjectinformationlength : u32) -> super::super::super::super::BOOL);
                windows_link::link!("kernel32.dll" "system" fn TerminateJobObject(hjob : super::super::Foundation:: HANDLE, uexitcode : u32) -> super::super::super::super::BOOL);
                pub type JOBOBJECTINFOCLASS = i32;
                #[repr(C)]
                #[derive(Clone, Copy, Default)]
                pub struct JOBOBJECT_BASIC_LIMIT_INFORMATION {
                    pub PerProcessUserTimeLimit: i64,
                    pub PerJobUserTimeLimit: i64,
                    pub LimitFlags: JOB_OBJECT_LIMIT,
                    pub MinimumWorkingSetSize: usize,
                    pub MaximumWorkingSetSize: usize,
                    pub ActiveProcessLimit: u32,
                    pub Affinity: usize,
                    pub PriorityClass: u32,
                    pub SchedulingClass: u32,
                }
                #[repr(C)]
                #[derive(Clone, Copy, Default)]
                pub struct JOBOBJECT_EXTENDED_LIMIT_INFORMATION {
                    pub BasicLimitInformation: JOBOBJECT_BASIC_LIMIT_INFORMATION,
                    pub IoInfo: super::Threading::IO_COUNTERS,
                    pub ProcessMemoryLimit: usize,
                    pub JobMemoryLimit: usize,
                    pub PeakProcessMemoryUsed: usize,
                    pub PeakJobMemoryUsed: usize,
                }
                pub type JOB_OBJECT_LIMIT = u32;
                pub const JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE: JOB_OBJECT_LIMIT = 8192u32;
                pub const JobObjectExtendedLimitInformation: JOBOBJECTINFOCLASS = 9i32;
            }
            pub mod Threading {
                windows_link::link!("kernel32.dll" "system" fn GetExitCodeProcess(hprocess : super::super::Foundation:: HANDLE, lpexitcode : *mut u32) -> super::super::super::super::BOOL);
                windows_link::link!("kernel32.dll" "system" fn OpenProcess(dwdesiredaccess : PROCESS_ACCESS_RIGHTS, binherithandle : super::super::super::super::BOOL, dwprocessid : u32) -> super::super::Foundation:: HANDLE);
                #[repr(C)]
                #[derive(Clone, Copy, Default)]
                pub struct IO_COUNTERS {
                    pub ReadOperationCount: u64,
                    pub WriteOperationCount: u64,
                    pub OtherOperationCount: u64,
                    pub ReadTransferCount: u64,
                    pub WriteTransferCount: u64,
                    pub OtherTransferCount: u64,
                }
                pub type PROCESS_ACCESS_RIGHTS = u32;
                pub const PROCESS_QUERY_LIMITED_INFORMATION: PROCESS_ACCESS_RIGHTS = 4096u32;
                pub const PROCESS_SET_QUOTA: PROCESS_ACCESS_RIGHTS = 256u32;
                pub const PROCESS_TERMINATE: PROCESS_ACCESS_RIGHTS = 1u32;
            }
        }
    }
}
