// Generated by windows-bindgen 0.100.0.
// Regenerate with `cargo run -p gpui_ce_windows_bindings`.

#![allow(non_snake_case, non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]

pub type BOOL = i32;
pub type PCWSTR = *const u16;
pub mod Windows {
    pub mod Win32 {
        windows_link::link!("kernel32.dll" "system" fn AssignProcessToJobObject(hjob : HANDLE, hprocess : HANDLE) -> super::super::BOOL);
        windows_link::link!("kernel32.dll" "system" fn CreateJobObjectW(lpjobattributes : *const SECURITY_ATTRIBUTES, lpname : super::super::PCWSTR) -> HANDLE);
        windows_link::link!("kernel32.dll" "system" fn GetExitCodeProcess(hprocess : HANDLE, lpexitcode : *mut u32) -> super::super::BOOL);
        windows_link::link!("kernel32.dll" "system" fn OpenProcess(dwdesiredaccess : u32, binherithandle : super::super::BOOL, dwprocessid : u32) -> HANDLE);
        windows_link::link!("kernel32.dll" "system" fn SetInformationJobObject(hjob : HANDLE, jobobjectinformationclass : JOBOBJECTINFOCLASS, lpjobobjectinformation : *const core::ffi::c_void, cbjobobjectinformationlength : u32) -> super::super::BOOL);
        windows_link::link!("kernel32.dll" "system" fn TerminateJobObject(hjob : HANDLE, uexitcode : u32) -> super::super::BOOL);
        pub type HANDLE = *mut core::ffi::c_void;
        #[repr(C)]
        #[derive(Clone, Copy, Default)]
        pub struct IO_COUNTERS {
            pub ReadOperationCount: u64,
            pub WriteOperationCount: u64,
            pub OtherOperationCount: u64,
            pub ReadTransferCount: u64,
            pub WriteTransferCount: u64,
            pub OtherTransferCount: u64,
        }
        pub type JOBOBJECTINFOCLASS = i32;
        #[repr(C)]
        #[derive(Clone, Copy, Default)]
        pub struct JOBOBJECT_BASIC_LIMIT_INFORMATION {
            pub PerProcessUserTimeLimit: i64,
            pub PerJobUserTimeLimit: i64,
            pub LimitFlags: u32,
            pub MinimumWorkingSetSize: usize,
            pub MaximumWorkingSetSize: usize,
            pub ActiveProcessLimit: u32,
            pub Affinity: usize,
            pub PriorityClass: u32,
            pub SchedulingClass: u32,
        }
        #[repr(C)]
        #[derive(Clone, Copy, Default)]
        pub struct JOBOBJECT_EXTENDED_LIMIT_INFORMATION {
            pub BasicLimitInformation: JOBOBJECT_BASIC_LIMIT_INFORMATION,
            pub IoInfo: IO_COUNTERS,
            pub ProcessMemoryLimit: usize,
            pub JobMemoryLimit: usize,
            pub PeakProcessMemoryUsed: usize,
            pub PeakJobMemoryUsed: usize,
        }
        pub const JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE: i32 = 8192;
        pub const JobObjectExtendedLimitInformation: JOBOBJECTINFOCLASS = 9;
        pub const PROCESS_QUERY_LIMITED_INFORMATION: i32 = 4096;
        pub const PROCESS_SET_QUOTA: i32 = 256;
        pub const PROCESS_TERMINATE: i32 = 1;
        #[repr(C)]
        #[derive(Clone, Copy, Default)]
        pub struct SECURITY_ATTRIBUTES {
            pub nLength: u32,
            pub lpSecurityDescriptor: *mut core::ffi::c_void,
            pub bInheritHandle: super::super::BOOL,
        }
        pub const STILL_ACTIVE: i32 = 259;
    }
}
