// Generated by windows-bindgen 0.100.0.
// Regenerate with `cargo run -p gpui_ce_windows_bindings`.

#![allow(non_snake_case, non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]

pub mod Windows {
    pub mod Win32 {
        windows_core::imp::define_interface!(
            ID3D11DeviceChild,
            ID3D11DeviceChild_Vtbl,
            0x1841e5c8_16b0_489b_bcc8_44cfb0d5deae
        );
        windows_core::imp::interface_hierarchy!(ID3D11DeviceChild, windows_core::IUnknown);
        #[repr(C)]
        pub struct ID3D11DeviceChild_Vtbl {
            pub base__: windows_core::IUnknown_Vtbl,
            GetDevice: usize,
            GetPrivateData: usize,
            SetPrivateData: usize,
            SetPrivateDataInterface: usize,
        }
        impl windows_core::RuntimeName for ID3D11DeviceChild {}
        windows_core::imp::define_interface!(
            ID3D11Resource,
            ID3D11Resource_Vtbl,
            0xdc8e63f3_d12b_4952_b47b_5e45026a862d
        );
        impl core::ops::Deref for ID3D11Resource {
            type Target = ID3D11DeviceChild;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11Resource,
            windows_core::IUnknown,
            ID3D11DeviceChild
        );
        #[repr(C)]
        pub struct ID3D11Resource_Vtbl {
            pub base__: ID3D11DeviceChild_Vtbl,
            GetType: usize,
            SetEvictionPriority: usize,
            GetEvictionPriority: usize,
        }
        impl windows_core::RuntimeName for ID3D11Resource {}
        windows_core::imp::define_interface!(
            ID3D11Texture2D,
            ID3D11Texture2D_Vtbl,
            0x6f15aaf2_d208_4e89_9ab4_489535d34f9c
        );
        impl core::ops::Deref for ID3D11Texture2D {
            type Target = ID3D11Resource;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11Texture2D,
            windows_core::IUnknown,
            ID3D11DeviceChild,
            ID3D11Resource
        );
        #[repr(C)]
        pub struct ID3D11Texture2D_Vtbl {
            pub base__: ID3D11Resource_Vtbl,
            GetDesc: usize,
        }
        impl windows_core::RuntimeName for ID3D11Texture2D {}
    }
}
