// Generated by windows-bindgen 0.100.0.
// Regenerate with `cargo run -p gpui_ce_windows_bindings`.

#![allow(non_snake_case, non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]

pub mod Windows {
    pub mod Win32 {
        #[inline]
        pub unsafe fn CloseHandle(hobject: HANDLE) -> windows_core::BOOL {
            windows_core::link!("kernel32.dll" "system" fn CloseHandle(hobject : HANDLE) -> windows_core::BOOL);
            unsafe { CloseHandle(hobject) }
        }
        pub type D3D11_BIND_FLAG = i32;
        pub const D3D11_BIND_SHADER_RESOURCE: D3D11_BIND_FLAG = 8;
        pub type D3D11_CPU_ACCESS_FLAG = i32;
        pub const D3D11_CPU_ACCESS_READ: D3D11_CPU_ACCESS_FLAG = 131072;
        pub type D3D11_FENCE_FLAG = u32;
        pub const D3D11_FENCE_FLAG_SHARED: D3D11_FENCE_FLAG = 2;
        pub type D3D11_MAP = i32;
        #[repr(C)]
        #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
        pub struct D3D11_MAPPED_SUBRESOURCE {
            pub pData: *mut core::ffi::c_void,
            pub RowPitch: u32,
            pub DepthPitch: u32,
        }
        pub const D3D11_MAP_READ: D3D11_MAP = 1;
        pub type D3D11_RESOURCE_MISC_FLAG = i32;
        pub const D3D11_RESOURCE_MISC_SHARED_NTHANDLE: D3D11_RESOURCE_MISC_FLAG = 2048;
        #[repr(C)]
        #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
        pub struct D3D11_SUBRESOURCE_DATA {
            pub pSysMem: *const core::ffi::c_void,
            pub SysMemPitch: u32,
            pub SysMemSlicePitch: u32,
        }
        #[repr(C)]
        #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
        pub struct D3D11_TEXTURE2D_DESC {
            pub Width: u32,
            pub Height: u32,
            pub MipLevels: u32,
            pub ArraySize: u32,
            pub Format: DXGI_FORMAT,
            pub SampleDesc: DXGI_SAMPLE_DESC,
            pub Usage: D3D11_USAGE,
            pub BindFlags: u32,
            pub CPUAccessFlags: u32,
            pub MiscFlags: u32,
        }
        pub type D3D11_USAGE = i32;
        pub const D3D11_USAGE_DEFAULT: D3D11_USAGE = 0;
        pub const D3D11_USAGE_STAGING: D3D11_USAGE = 3;
        pub type DXGI_FORMAT = i32;
        pub const DXGI_FORMAT_B8G8R8A8_TYPELESS: DXGI_FORMAT = 90;
        pub const DXGI_FORMAT_B8G8R8A8_UNORM: DXGI_FORMAT = 87;
        pub const DXGI_FORMAT_B8G8R8A8_UNORM_SRGB: DXGI_FORMAT = 91;
        #[repr(C)]
        #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
        pub struct DXGI_SAMPLE_DESC {
            pub Count: u32,
            pub Quality: u32,
        }
        pub const GENERIC_ALL: i32 = 268435456;
        #[repr(transparent)]
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
        pub struct HANDLE(pub *mut core::ffi::c_void);
        windows_core::imp::define_interface!(
            ID3D11Device,
            ID3D11Device_Vtbl,
            0xdb6f6ddb_ac77_4e88_8253_819df9bbf140
        );
        windows_core::imp::interface_hierarchy!(ID3D11Device, windows_core::IUnknown);
        impl ID3D11Device {
            pub unsafe fn CreateTexture2D(
                &self,
                pdesc: *const D3D11_TEXTURE2D_DESC,
                pinitialdata: Option<*const D3D11_SUBRESOURCE_DATA>,
                pptexture2d: Option<*mut Option<ID3D11Texture2D>>,
            ) -> windows_core::HRESULT {
                unsafe {
                    (windows_core::Interface::vtable(self).CreateTexture2D)(
                        windows_core::Interface::as_raw(self),
                        pdesc,
                        pinitialdata.unwrap_or(core::mem::zeroed()) as _,
                        pptexture2d.unwrap_or(core::mem::zeroed()) as _,
                    )
                }
            }
            pub unsafe fn GetImmediateContext(&self) -> windows_core::Result<ID3D11DeviceContext> {
                unsafe {
                    let mut result__ = core::mem::zeroed();
                    (windows_core::Interface::vtable(self).GetImmediateContext)(
                        windows_core::Interface::as_raw(self),
                        &mut result__,
                    );
                    windows_core::imp::Type::from_abi(result__)
                }
            }
        }
        #[repr(C)]
        pub struct ID3D11Device_Vtbl {
            pub base__: windows_core::IUnknown_Vtbl,
            CreateBuffer: usize,
            CreateTexture1D: usize,
            pub CreateTexture2D: unsafe extern "system" fn(
                *mut core::ffi::c_void,
                *const D3D11_TEXTURE2D_DESC,
                *const D3D11_SUBRESOURCE_DATA,
                *mut *mut core::ffi::c_void,
            ) -> windows_core::HRESULT,
            CreateTexture3D: usize,
            CreateShaderResourceView: usize,
            CreateUnorderedAccessView: usize,
            CreateRenderTargetView: usize,
            CreateDepthStencilView: usize,
            CreateInputLayout: usize,
            CreateVertexShader: usize,
            CreateGeometryShader: usize,
            CreateGeometryShaderWithStreamOutput: usize,
            CreatePixelShader: usize,
            CreateHullShader: usize,
            CreateDomainShader: usize,
            CreateComputeShader: usize,
            CreateClassLinkage: usize,
            CreateBlendState: usize,
            CreateDepthStencilState: usize,
            CreateRasterizerState: usize,
            CreateSamplerState: usize,
            CreateQuery: usize,
            CreatePredicate: usize,
            CreateCounter: usize,
            CreateDeferredContext: usize,
            OpenSharedResource: usize,
            CheckFormatSupport: usize,
            CheckMultisampleQualityLevels: usize,
            CheckCounterInfo: usize,
            CheckCounter: usize,
            CheckFeatureSupport: usize,
            GetPrivateData: usize,
            SetPrivateData: usize,
            SetPrivateDataInterface: usize,
            GetFeatureLevel: usize,
            GetCreationFlags: usize,
            GetDeviceRemovedReason: usize,
            pub GetImmediateContext:
                unsafe extern "system" fn(*mut core::ffi::c_void, *mut *mut core::ffi::c_void),
            SetExceptionMode: usize,
            GetExceptionMode: usize,
        }
        impl windows_core::RuntimeName for ID3D11Device {}
        windows_core::imp::define_interface!(
            ID3D11Device1,
            ID3D11Device1_Vtbl,
            0xa04bfb29_08ef_43d6_a49c_a9bdbdcbe686
        );
        impl core::ops::Deref for ID3D11Device1 {
            type Target = ID3D11Device;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11Device1,
            windows_core::IUnknown,
            ID3D11Device
        );
        #[repr(C)]
        pub struct ID3D11Device1_Vtbl {
            pub base__: ID3D11Device_Vtbl,
            GetImmediateContext1: usize,
            CreateDeferredContext1: usize,
            CreateBlendState1: usize,
            CreateRasterizerState1: usize,
            CreateDeviceContextState: usize,
            OpenSharedResource1: usize,
            OpenSharedResourceByName: usize,
        }
        impl windows_core::RuntimeName for ID3D11Device1 {}
        windows_core::imp::define_interface!(
            ID3D11Device2,
            ID3D11Device2_Vtbl,
            0x9d06dffa_d1e5_4d07_83a8_1bb123f2f841
        );
        impl core::ops::Deref for ID3D11Device2 {
            type Target = ID3D11Device1;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11Device2,
            windows_core::IUnknown,
            ID3D11Device,
            ID3D11Device1
        );
        #[repr(C)]
        pub struct ID3D11Device2_Vtbl {
            pub base__: ID3D11Device1_Vtbl,
            GetImmediateContext2: usize,
            CreateDeferredContext2: usize,
            GetResourceTiling: usize,
            CheckMultisampleQualityLevels1: usize,
        }
        impl windows_core::RuntimeName for ID3D11Device2 {}
        windows_core::imp::define_interface!(
            ID3D11Device3,
            ID3D11Device3_Vtbl,
            0xa05c8c37_d2c6_4732_b3a0_9ce0b0dc9ae6
        );
        impl core::ops::Deref for ID3D11Device3 {
            type Target = ID3D11Device2;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11Device3,
            windows_core::IUnknown,
            ID3D11Device,
            ID3D11Device1,
            ID3D11Device2
        );
        #[repr(C)]
        pub struct ID3D11Device3_Vtbl {
            pub base__: ID3D11Device2_Vtbl,
            CreateTexture2D1: usize,
            CreateTexture3D1: usize,
            CreateRasterizerState2: usize,
            CreateShaderResourceView1: usize,
            CreateUnorderedAccessView1: usize,
            CreateRenderTargetView1: usize,
            CreateQuery1: usize,
            GetImmediateContext3: usize,
            CreateDeferredContext3: usize,
            WriteToSubresource: usize,
            ReadFromSubresource: usize,
        }
        impl windows_core::RuntimeName for ID3D11Device3 {}
        windows_core::imp::define_interface!(
            ID3D11Device4,
            ID3D11Device4_Vtbl,
            0x8992ab71_02e6_4b8d_ba48_b056dcda42c4
        );
        impl core::ops::Deref for ID3D11Device4 {
            type Target = ID3D11Device3;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11Device4,
            windows_core::IUnknown,
            ID3D11Device,
            ID3D11Device1,
            ID3D11Device2,
            ID3D11Device3
        );
        #[repr(C)]
        pub struct ID3D11Device4_Vtbl {
            pub base__: ID3D11Device3_Vtbl,
            RegisterDeviceRemovedEvent: usize,
            UnregisterDeviceRemoved: usize,
        }
        impl windows_core::RuntimeName for ID3D11Device4 {}
        windows_core::imp::define_interface!(
            ID3D11Device5,
            ID3D11Device5_Vtbl,
            0x8ffde202_a0e7_45df_9e01_e837801b5ea0
        );
        impl core::ops::Deref for ID3D11Device5 {
            type Target = ID3D11Device4;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11Device5,
            windows_core::IUnknown,
            ID3D11Device,
            ID3D11Device1,
            ID3D11Device2,
            ID3D11Device3,
            ID3D11Device4
        );
        impl ID3D11Device5 {
            pub unsafe fn CreateFence<T>(
                &self,
                initialvalue: u64,
                flags: D3D11_FENCE_FLAG,
                result__: *mut Option<T>,
            ) -> windows_core::Result<()>
            where
                T: windows_core::Interface,
            {
                unsafe {
                    (windows_core::Interface::vtable(self).CreateFence)(
                        windows_core::Interface::as_raw(self),
                        initialvalue,
                        flags,
                        &T::IID,
                        result__ as *mut _ as *mut _,
                    )
                    .ok()
                }
            }
        }
        #[repr(C)]
        pub struct ID3D11Device5_Vtbl {
            pub base__: ID3D11Device4_Vtbl,
            OpenSharedFence: usize,
            pub CreateFence: unsafe extern "system" fn(
                *mut core::ffi::c_void,
                u64,
                D3D11_FENCE_FLAG,
                *const windows_core::GUID,
                *mut *mut core::ffi::c_void,
            ) -> windows_core::HRESULT,
        }
        impl windows_core::RuntimeName for ID3D11Device5 {}
        windows_core::imp::define_interface!(
            ID3D11DeviceChild,
            ID3D11DeviceChild_Vtbl,
            0x1841e5c8_16b0_489b_bcc8_44cfb0d5deae
        );
        windows_core::imp::interface_hierarchy!(ID3D11DeviceChild, windows_core::IUnknown);
        impl ID3D11DeviceChild {
            pub unsafe fn GetDevice(&self) -> windows_core::Result<ID3D11Device> {
                unsafe {
                    let mut result__ = core::mem::zeroed();
                    (windows_core::Interface::vtable(self).GetDevice)(
                        windows_core::Interface::as_raw(self),
                        &mut result__,
                    );
                    windows_core::imp::Type::from_abi(result__)
                }
            }
        }
        #[repr(C)]
        pub struct ID3D11DeviceChild_Vtbl {
            pub base__: windows_core::IUnknown_Vtbl,
            pub GetDevice:
                unsafe extern "system" fn(*mut core::ffi::c_void, *mut *mut core::ffi::c_void),
            GetPrivateData: usize,
            SetPrivateData: usize,
            SetPrivateDataInterface: usize,
        }
        impl windows_core::RuntimeName for ID3D11DeviceChild {}
        windows_core::imp::define_interface!(
            ID3D11DeviceContext,
            ID3D11DeviceContext_Vtbl,
            0xc0bfa96c_e089_44fb_8eaf_26f8796190da
        );
        impl core::ops::Deref for ID3D11DeviceContext {
            type Target = ID3D11DeviceChild;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11DeviceContext,
            windows_core::IUnknown,
            ID3D11DeviceChild
        );
        impl ID3D11DeviceContext {
            pub unsafe fn Map<P0>(
                &self,
                presource: P0,
                subresource: u32,
                maptype: D3D11_MAP,
                mapflags: u32,
                pmappedresource: Option<*mut D3D11_MAPPED_SUBRESOURCE>,
            ) -> windows_core::HRESULT
            where
                P0: windows_core::Param<ID3D11Resource>,
            {
                unsafe {
                    (windows_core::Interface::vtable(self).Map)(
                        windows_core::Interface::as_raw(self),
                        presource.param().abi(),
                        subresource,
                        maptype,
                        mapflags,
                        pmappedresource.unwrap_or(core::mem::zeroed()) as _,
                    )
                }
            }
            pub unsafe fn Unmap<P0>(&self, presource: P0, subresource: u32)
            where
                P0: windows_core::Param<ID3D11Resource>,
            {
                unsafe {
                    (windows_core::Interface::vtable(self).Unmap)(
                        windows_core::Interface::as_raw(self),
                        presource.param().abi(),
                        subresource,
                    );
                }
            }
            pub unsafe fn CopyResource<P0, P1>(&self, pdstresource: P0, psrcresource: P1)
            where
                P0: windows_core::Param<ID3D11Resource>,
                P1: windows_core::Param<ID3D11Resource>,
            {
                unsafe {
                    (windows_core::Interface::vtable(self).CopyResource)(
                        windows_core::Interface::as_raw(self),
                        pdstresource.param().abi(),
                        psrcresource.param().abi(),
                    );
                }
            }
            pub unsafe fn Flush(&self) {
                unsafe {
                    (windows_core::Interface::vtable(self).Flush)(windows_core::Interface::as_raw(
                        self,
                    ));
                }
            }
        }
        #[repr(C)]
        pub struct ID3D11DeviceContext_Vtbl {
            pub base__: ID3D11DeviceChild_Vtbl,
            VSSetConstantBuffers: usize,
            PSSetShaderResources: usize,
            PSSetShader: usize,
            PSSetSamplers: usize,
            VSSetShader: usize,
            DrawIndexed: usize,
            Draw: usize,
            pub Map: unsafe extern "system" fn(
                *mut core::ffi::c_void,
                *mut core::ffi::c_void,
                u32,
                D3D11_MAP,
                u32,
                *mut D3D11_MAPPED_SUBRESOURCE,
            ) -> windows_core::HRESULT,
            pub Unmap:
                unsafe extern "system" fn(*mut core::ffi::c_void, *mut core::ffi::c_void, u32),
            PSSetConstantBuffers: usize,
            IASetInputLayout: usize,
            IASetVertexBuffers: usize,
            IASetIndexBuffer: usize,
            DrawIndexedInstanced: usize,
            DrawInstanced: usize,
            GSSetConstantBuffers: usize,
            GSSetShader: usize,
            IASetPrimitiveTopology: usize,
            VSSetShaderResources: usize,
            VSSetSamplers: usize,
            Begin: usize,
            End: usize,
            GetData: usize,
            SetPredication: usize,
            GSSetShaderResources: usize,
            GSSetSamplers: usize,
            OMSetRenderTargets: usize,
            OMSetRenderTargetsAndUnorderedAccessViews: usize,
            OMSetBlendState: usize,
            OMSetDepthStencilState: usize,
            SOSetTargets: usize,
            DrawAuto: usize,
            DrawIndexedInstancedIndirect: usize,
            DrawInstancedIndirect: usize,
            Dispatch: usize,
            DispatchIndirect: usize,
            RSSetState: usize,
            RSSetViewports: usize,
            RSSetScissorRects: usize,
            CopySubresourceRegion: usize,
            pub CopyResource: unsafe extern "system" fn(
                *mut core::ffi::c_void,
                *mut core::ffi::c_void,
                *mut core::ffi::c_void,
            ),
            UpdateSubresource: usize,
            CopyStructureCount: usize,
            ClearRenderTargetView: usize,
            ClearUnorderedAccessViewUint: usize,
            ClearUnorderedAccessViewFloat: usize,
            ClearDepthStencilView: usize,
            GenerateMips: usize,
            SetResourceMinLOD: usize,
            GetResourceMinLOD: usize,
            ResolveSubresource: usize,
            ExecuteCommandList: usize,
            HSSetShaderResources: usize,
            HSSetShader: usize,
            HSSetSamplers: usize,
            HSSetConstantBuffers: usize,
            DSSetShaderResources: usize,
            DSSetShader: usize,
            DSSetSamplers: usize,
            DSSetConstantBuffers: usize,
            CSSetShaderResources: usize,
            CSSetUnorderedAccessViews: usize,
            CSSetShader: usize,
            CSSetSamplers: usize,
            CSSetConstantBuffers: usize,
            VSGetConstantBuffers: usize,
            PSGetShaderResources: usize,
            PSGetShader: usize,
            PSGetSamplers: usize,
            VSGetShader: usize,
            PSGetConstantBuffers: usize,
            IAGetInputLayout: usize,
            IAGetVertexBuffers: usize,
            IAGetIndexBuffer: usize,
            GSGetConstantBuffers: usize,
            GSGetShader: usize,
            IAGetPrimitiveTopology: usize,
            VSGetShaderResources: usize,
            VSGetSamplers: usize,
            GetPredication: usize,
            GSGetShaderResources: usize,
            GSGetSamplers: usize,
            OMGetRenderTargets: usize,
            OMGetRenderTargetsAndUnorderedAccessViews: usize,
            OMGetBlendState: usize,
            OMGetDepthStencilState: usize,
            SOGetTargets: usize,
            RSGetState: usize,
            RSGetViewports: usize,
            RSGetScissorRects: usize,
            HSGetShaderResources: usize,
            HSGetShader: usize,
            HSGetSamplers: usize,
            HSGetConstantBuffers: usize,
            DSGetShaderResources: usize,
            DSGetShader: usize,
            DSGetSamplers: usize,
            DSGetConstantBuffers: usize,
            CSGetShaderResources: usize,
            CSGetUnorderedAccessViews: usize,
            CSGetShader: usize,
            CSGetSamplers: usize,
            CSGetConstantBuffers: usize,
            ClearState: usize,
            pub Flush: unsafe extern "system" fn(*mut core::ffi::c_void),
            GetType: usize,
            GetContextFlags: usize,
            FinishCommandList: usize,
        }
        impl windows_core::RuntimeName for ID3D11DeviceContext {}
        windows_core::imp::define_interface!(
            ID3D11DeviceContext1,
            ID3D11DeviceContext1_Vtbl,
            0xbb2c6faa_b5fb_4082_8e6b_388b8cfa90e1
        );
        impl core::ops::Deref for ID3D11DeviceContext1 {
            type Target = ID3D11DeviceContext;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11DeviceContext1,
            windows_core::IUnknown,
            ID3D11DeviceChild,
            ID3D11DeviceContext
        );
        #[repr(C)]
        pub struct ID3D11DeviceContext1_Vtbl {
            pub base__: ID3D11DeviceContext_Vtbl,
            CopySubresourceRegion1: usize,
            UpdateSubresource1: usize,
            DiscardResource: usize,
            DiscardView: usize,
            VSSetConstantBuffers1: usize,
            HSSetConstantBuffers1: usize,
            DSSetConstantBuffers1: usize,
            GSSetConstantBuffers1: usize,
            PSSetConstantBuffers1: usize,
            CSSetConstantBuffers1: usize,
            VSGetConstantBuffers1: usize,
            HSGetConstantBuffers1: usize,
            DSGetConstantBuffers1: usize,
            GSGetConstantBuffers1: usize,
            PSGetConstantBuffers1: usize,
            CSGetConstantBuffers1: usize,
            SwapDeviceContextState: usize,
            ClearView: usize,
            DiscardView1: usize,
        }
        impl windows_core::RuntimeName for ID3D11DeviceContext1 {}
        windows_core::imp::define_interface!(
            ID3D11DeviceContext2,
            ID3D11DeviceContext2_Vtbl,
            0x420d5b32_b90c_4da4_bef0_359f6a24a83a
        );
        impl core::ops::Deref for ID3D11DeviceContext2 {
            type Target = ID3D11DeviceContext1;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11DeviceContext2,
            windows_core::IUnknown,
            ID3D11DeviceChild,
            ID3D11DeviceContext,
            ID3D11DeviceContext1
        );
        #[repr(C)]
        pub struct ID3D11DeviceContext2_Vtbl {
            pub base__: ID3D11DeviceContext1_Vtbl,
            UpdateTileMappings: usize,
            CopyTileMappings: usize,
            CopyTiles: usize,
            UpdateTiles: usize,
            ResizeTilePool: usize,
            TiledResourceBarrier: usize,
            IsAnnotationEnabled: usize,
            SetMarkerInt: usize,
            BeginEventInt: usize,
            EndEvent: usize,
        }
        impl windows_core::RuntimeName for ID3D11DeviceContext2 {}
        windows_core::imp::define_interface!(
            ID3D11DeviceContext3,
            ID3D11DeviceContext3_Vtbl,
            0xb4e3c01d_e79e_4637_91b2_510e9f4c9b8f
        );
        impl core::ops::Deref for ID3D11DeviceContext3 {
            type Target = ID3D11DeviceContext2;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11DeviceContext3,
            windows_core::IUnknown,
            ID3D11DeviceChild,
            ID3D11DeviceContext,
            ID3D11DeviceContext1,
            ID3D11DeviceContext2
        );
        #[repr(C)]
        pub struct ID3D11DeviceContext3_Vtbl {
            pub base__: ID3D11DeviceContext2_Vtbl,
            Flush1: usize,
            SetHardwareProtectionState: usize,
            GetHardwareProtectionState: usize,
        }
        impl windows_core::RuntimeName for ID3D11DeviceContext3 {}
        windows_core::imp::define_interface!(
            ID3D11DeviceContext4,
            ID3D11DeviceContext4_Vtbl,
            0x917600da_f58c_4c33_98d8_3e15b390fa24
        );
        impl core::ops::Deref for ID3D11DeviceContext4 {
            type Target = ID3D11DeviceContext3;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11DeviceContext4,
            windows_core::IUnknown,
            ID3D11DeviceChild,
            ID3D11DeviceContext,
            ID3D11DeviceContext1,
            ID3D11DeviceContext2,
            ID3D11DeviceContext3
        );
        impl ID3D11DeviceContext4 {
            pub unsafe fn Signal<P0>(&self, pfence: P0, value: u64) -> windows_core::HRESULT
            where
                P0: windows_core::Param<ID3D11Fence>,
            {
                unsafe {
                    (windows_core::Interface::vtable(self).Signal)(
                        windows_core::Interface::as_raw(self),
                        pfence.param().abi(),
                        value,
                    )
                }
            }
        }
        #[repr(C)]
        pub struct ID3D11DeviceContext4_Vtbl {
            pub base__: ID3D11DeviceContext3_Vtbl,
            pub Signal: unsafe extern "system" fn(
                *mut core::ffi::c_void,
                *mut core::ffi::c_void,
                u64,
            ) -> windows_core::HRESULT,
            Wait: usize,
        }
        impl windows_core::RuntimeName for ID3D11DeviceContext4 {}
        windows_core::imp::define_interface!(
            ID3D11Fence,
            ID3D11Fence_Vtbl,
            0xaffde9d1_1df7_4bb7_8a34_0f46251dab80
        );
        impl core::ops::Deref for ID3D11Fence {
            type Target = ID3D11DeviceChild;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11Fence,
            windows_core::IUnknown,
            ID3D11DeviceChild
        );
        impl ID3D11Fence {
            pub unsafe fn CreateSharedHandle<P2>(
                &self,
                pattributes: Option<*const SECURITY_ATTRIBUTES>,
                dwaccess: u32,
                lpname: P2,
            ) -> windows_core::Result<HANDLE>
            where
                P2: windows_core::Param<windows_core::PCWSTR>,
            {
                unsafe {
                    let mut result__ = core::mem::zeroed();
                    (windows_core::Interface::vtable(self).CreateSharedHandle)(
                        windows_core::Interface::as_raw(self),
                        pattributes.unwrap_or(core::mem::zeroed()) as _,
                        dwaccess,
                        lpname.param().abi(),
                        &mut result__,
                    )
                    .map(|| result__)
                }
            }
        }
        #[repr(C)]
        pub struct ID3D11Fence_Vtbl {
            pub base__: ID3D11DeviceChild_Vtbl,
            pub CreateSharedHandle: unsafe extern "system" fn(
                *mut core::ffi::c_void,
                *const SECURITY_ATTRIBUTES,
                u32,
                windows_core::PCWSTR,
                *mut HANDLE,
            ) -> windows_core::HRESULT,
            GetCompletedValue: usize,
            SetEventOnCompletion: usize,
        }
        impl windows_core::RuntimeName for ID3D11Fence {}
        windows_core::imp::define_interface!(
            ID3D11Resource,
            ID3D11Resource_Vtbl,
            0xdc8e63f3_d12b_4952_b47b_5e45026a862d
        );
        impl core::ops::Deref for ID3D11Resource {
            type Target = ID3D11DeviceChild;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11Resource,
            windows_core::IUnknown,
            ID3D11DeviceChild
        );
        #[repr(C)]
        pub struct ID3D11Resource_Vtbl {
            pub base__: ID3D11DeviceChild_Vtbl,
            GetType: usize,
            SetEvictionPriority: usize,
            GetEvictionPriority: usize,
        }
        impl windows_core::RuntimeName for ID3D11Resource {}
        windows_core::imp::define_interface!(
            ID3D11Texture2D,
            ID3D11Texture2D_Vtbl,
            0x6f15aaf2_d208_4e89_9ab4_489535d34f9c
        );
        impl core::ops::Deref for ID3D11Texture2D {
            type Target = ID3D11Resource;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D11Texture2D,
            windows_core::IUnknown,
            ID3D11DeviceChild,
            ID3D11Resource
        );
        impl ID3D11Texture2D {
            pub unsafe fn GetDesc(&self, pdesc: *mut D3D11_TEXTURE2D_DESC) {
                unsafe {
                    (windows_core::Interface::vtable(self).GetDesc)(
                        windows_core::Interface::as_raw(self),
                        pdesc as _,
                    );
                }
            }
        }
        #[repr(C)]
        pub struct ID3D11Texture2D_Vtbl {
            pub base__: ID3D11Resource_Vtbl,
            pub GetDesc:
                unsafe extern "system" fn(*mut core::ffi::c_void, *mut D3D11_TEXTURE2D_DESC),
        }
        impl windows_core::RuntimeName for ID3D11Texture2D {}
        windows_core::imp::define_interface!(
            ID3D12CommandQueue,
            ID3D12CommandQueue_Vtbl,
            0x0ec870a6_5d7e_4c22_8cfc_5baae07616ed
        );
        impl core::ops::Deref for ID3D12CommandQueue {
            type Target = ID3D12Pageable;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D12CommandQueue,
            windows_core::IUnknown,
            ID3D12Object,
            ID3D12DeviceChild,
            ID3D12Pageable
        );
        impl ID3D12CommandQueue {
            pub unsafe fn Wait<P0>(&self, pfence: P0, value: u64) -> windows_core::HRESULT
            where
                P0: windows_core::Param<ID3D12Fence>,
            {
                unsafe {
                    (windows_core::Interface::vtable(self).Wait)(
                        windows_core::Interface::as_raw(self),
                        pfence.param().abi(),
                        value,
                    )
                }
            }
        }
        #[repr(C)]
        pub struct ID3D12CommandQueue_Vtbl {
            pub base__: ID3D12Pageable_Vtbl,
            UpdateTileMappings: usize,
            CopyTileMappings: usize,
            ExecuteCommandLists: usize,
            SetMarker: usize,
            BeginEvent: usize,
            EndEvent: usize,
            Signal: usize,
            pub Wait: unsafe extern "system" fn(
                *mut core::ffi::c_void,
                *mut core::ffi::c_void,
                u64,
            ) -> windows_core::HRESULT,
            GetTimestampFrequency: usize,
            GetClockCalibration: usize,
            GetDesc: usize,
        }
        impl windows_core::RuntimeName for ID3D12CommandQueue {}
        windows_core::imp::define_interface!(
            ID3D12Device,
            ID3D12Device_Vtbl,
            0x189819f1_1db6_4b57_be54_1821339b85f7
        );
        impl core::ops::Deref for ID3D12Device {
            type Target = ID3D12Object;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(ID3D12Device, windows_core::IUnknown, ID3D12Object);
        impl ID3D12Device {
            pub unsafe fn OpenSharedHandle<T>(
                &self,
                nthandle: HANDLE,
                result__: *mut Option<T>,
            ) -> windows_core::Result<()>
            where
                T: windows_core::Interface,
            {
                unsafe {
                    (windows_core::Interface::vtable(self).OpenSharedHandle)(
                        windows_core::Interface::as_raw(self),
                        nthandle,
                        &T::IID,
                        result__ as *mut _ as *mut _,
                    )
                    .ok()
                }
            }
        }
        #[repr(C)]
        pub struct ID3D12Device_Vtbl {
            pub base__: ID3D12Object_Vtbl,
            GetNodeCount: usize,
            CreateCommandQueue: usize,
            CreateCommandAllocator: usize,
            CreateGraphicsPipelineState: usize,
            CreateComputePipelineState: usize,
            CreateCommandList: usize,
            CheckFeatureSupport: usize,
            CreateDescriptorHeap: usize,
            GetDescriptorHandleIncrementSize: usize,
            CreateRootSignature: usize,
            CreateConstantBufferView: usize,
            CreateShaderResourceView: usize,
            CreateUnorderedAccessView: usize,
            CreateRenderTargetView: usize,
            CreateDepthStencilView: usize,
            CreateSampler: usize,
            CopyDescriptors: usize,
            CopyDescriptorsSimple: usize,
            GetResourceAllocationInfo: usize,
            GetCustomHeapProperties: usize,
            CreateCommittedResource: usize,
            CreateHeap: usize,
            CreatePlacedResource: usize,
            CreateReservedResource: usize,
            CreateSharedHandle: usize,
            pub OpenSharedHandle: unsafe extern "system" fn(
                *mut core::ffi::c_void,
                HANDLE,
                *const windows_core::GUID,
                *mut *mut core::ffi::c_void,
            ) -> windows_core::HRESULT,
            OpenSharedHandleByName: usize,
            MakeResident: usize,
            Evict: usize,
            CreateFence: usize,
            GetDeviceRemovedReason: usize,
            GetCopyableFootprints: usize,
            CreateQueryHeap: usize,
            SetStablePowerState: usize,
            CreateCommandSignature: usize,
            GetResourceTiling: usize,
            GetAdapterLuid: usize,
        }
        impl windows_core::RuntimeName for ID3D12Device {}
        windows_core::imp::define_interface!(
            ID3D12DeviceChild,
            ID3D12DeviceChild_Vtbl,
            0x905db94b_a00c_4140_9df5_2b64ca9ea357
        );
        impl core::ops::Deref for ID3D12DeviceChild {
            type Target = ID3D12Object;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D12DeviceChild,
            windows_core::IUnknown,
            ID3D12Object
        );
        #[repr(C)]
        pub struct ID3D12DeviceChild_Vtbl {
            pub base__: ID3D12Object_Vtbl,
            GetDevice: usize,
        }
        impl windows_core::RuntimeName for ID3D12DeviceChild {}
        windows_core::imp::define_interface!(
            ID3D12Fence,
            ID3D12Fence_Vtbl,
            0x0a753dcf_c4d8_4b91_adf6_be5a60d95a76
        );
        impl core::ops::Deref for ID3D12Fence {
            type Target = ID3D12Pageable;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D12Fence,
            windows_core::IUnknown,
            ID3D12Object,
            ID3D12DeviceChild,
            ID3D12Pageable
        );
        #[repr(C)]
        pub struct ID3D12Fence_Vtbl {
            pub base__: ID3D12Pageable_Vtbl,
            GetCompletedValue: usize,
            SetEventOnCompletion: usize,
            Signal: usize,
        }
        impl windows_core::RuntimeName for ID3D12Fence {}
        windows_core::imp::define_interface!(
            ID3D12Object,
            ID3D12Object_Vtbl,
            0xc4fec28f_7966_4e95_9f94_f431cb56c3b8
        );
        windows_core::imp::interface_hierarchy!(ID3D12Object, windows_core::IUnknown);
        #[repr(C)]
        pub struct ID3D12Object_Vtbl {
            pub base__: windows_core::IUnknown_Vtbl,
            GetPrivateData: usize,
            SetPrivateData: usize,
            SetPrivateDataInterface: usize,
            SetName: usize,
        }
        impl windows_core::RuntimeName for ID3D12Object {}
        windows_core::imp::define_interface!(
            ID3D12Pageable,
            ID3D12Pageable_Vtbl,
            0x63ee58fb_1268_4835_86da_f008ce62f0d6
        );
        impl core::ops::Deref for ID3D12Pageable {
            type Target = ID3D12DeviceChild;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D12Pageable,
            windows_core::IUnknown,
            ID3D12Object,
            ID3D12DeviceChild
        );
        #[repr(C)]
        pub struct ID3D12Pageable_Vtbl {
            pub base__: ID3D12DeviceChild_Vtbl,
        }
        impl windows_core::RuntimeName for ID3D12Pageable {}
        windows_core::imp::define_interface!(
            ID3D12Resource,
            ID3D12Resource_Vtbl,
            0x696442be_a72e_4059_bc79_5b5c98040fad
        );
        impl core::ops::Deref for ID3D12Resource {
            type Target = ID3D12Pageable;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            ID3D12Resource,
            windows_core::IUnknown,
            ID3D12Object,
            ID3D12DeviceChild,
            ID3D12Pageable
        );
        #[repr(C)]
        pub struct ID3D12Resource_Vtbl {
            pub base__: ID3D12Pageable_Vtbl,
            Map: usize,
            Unmap: usize,
            GetDesc: usize,
            GetGPUVirtualAddress: usize,
            WriteToSubresource: usize,
            ReadFromSubresource: usize,
            GetHeapProperties: usize,
        }
        impl windows_core::RuntimeName for ID3D12Resource {}
        windows_core::imp::define_interface!(
            IDXGIDeviceSubObject,
            IDXGIDeviceSubObject_Vtbl,
            0x3d3e0379_f9de_4d58_bb6c_18d62992f1a6
        );
        impl core::ops::Deref for IDXGIDeviceSubObject {
            type Target = IDXGIObject;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            IDXGIDeviceSubObject,
            windows_core::IUnknown,
            IDXGIObject
        );
        #[repr(C)]
        pub struct IDXGIDeviceSubObject_Vtbl {
            pub base__: IDXGIObject_Vtbl,
            GetDevice: usize,
        }
        impl windows_core::RuntimeName for IDXGIDeviceSubObject {}
        windows_core::imp::define_interface!(
            IDXGIObject,
            IDXGIObject_Vtbl,
            0xaec22fb8_76f3_4639_9be0_28eb43a67a2e
        );
        windows_core::imp::interface_hierarchy!(IDXGIObject, windows_core::IUnknown);
        #[repr(C)]
        pub struct IDXGIObject_Vtbl {
            pub base__: windows_core::IUnknown_Vtbl,
            SetPrivateData: usize,
            SetPrivateDataInterface: usize,
            GetPrivateData: usize,
            GetParent: usize,
        }
        impl windows_core::RuntimeName for IDXGIObject {}
        windows_core::imp::define_interface!(
            IDXGIResource,
            IDXGIResource_Vtbl,
            0x035f3ab4_482e_4e50_b41f_8a7f8bd8960b
        );
        impl core::ops::Deref for IDXGIResource {
            type Target = IDXGIDeviceSubObject;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            IDXGIResource,
            windows_core::IUnknown,
            IDXGIObject,
            IDXGIDeviceSubObject
        );
        #[repr(C)]
        pub struct IDXGIResource_Vtbl {
            pub base__: IDXGIDeviceSubObject_Vtbl,
            GetSharedHandle: usize,
            GetUsage: usize,
            SetEvictionPriority: usize,
            GetEvictionPriority: usize,
        }
        impl windows_core::RuntimeName for IDXGIResource {}
        windows_core::imp::define_interface!(
            IDXGIResource1,
            IDXGIResource1_Vtbl,
            0x30961379_4609_4a41_998e_54fe567ee0c1
        );
        impl core::ops::Deref for IDXGIResource1 {
            type Target = IDXGIResource;
            fn deref(&self) -> &Self::Target {
                unsafe { core::mem::transmute(self) }
            }
        }
        windows_core::imp::interface_hierarchy!(
            IDXGIResource1,
            windows_core::IUnknown,
            IDXGIObject,
            IDXGIDeviceSubObject,
            IDXGIResource
        );
        impl IDXGIResource1 {
            pub unsafe fn CreateSharedHandle<P2>(
                &self,
                pattributes: Option<*const SECURITY_ATTRIBUTES>,
                dwaccess: u32,
                lpname: P2,
            ) -> windows_core::Result<HANDLE>
            where
                P2: windows_core::Param<windows_core::PCWSTR>,
            {
                unsafe {
                    let mut result__ = core::mem::zeroed();
                    (windows_core::Interface::vtable(self).CreateSharedHandle)(
                        windows_core::Interface::as_raw(self),
                        pattributes.unwrap_or(core::mem::zeroed()) as _,
                        dwaccess,
                        lpname.param().abi(),
                        &mut result__,
                    )
                    .map(|| result__)
                }
            }
        }
        #[repr(C)]
        pub struct IDXGIResource1_Vtbl {
            pub base__: IDXGIResource_Vtbl,
            CreateSubresourceSurface: usize,
            pub CreateSharedHandle: unsafe extern "system" fn(
                *mut core::ffi::c_void,
                *const SECURITY_ATTRIBUTES,
                u32,
                windows_core::PCWSTR,
                *mut HANDLE,
            ) -> windows_core::HRESULT,
        }
        impl windows_core::RuntimeName for IDXGIResource1 {}
        #[repr(C)]
        #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
        pub struct SECURITY_ATTRIBUTES {
            pub nLength: u32,
            pub lpSecurityDescriptor: *mut core::ffi::c_void,
            pub bInheritHandle: windows_core::BOOL,
        }
    }
}
