// Generated by windows-bindgen 0.100.0.
// Regenerate with `cargo run -p gpui_ce_windows_bindings`.

#![allow(non_snake_case, non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]

pub mod Windows {
    pub mod Win32 {
        #[inline]
        pub unsafe fn D3DCompile<P2, P4, P5, P6>(
            psrcdata: *const core::ffi::c_void,
            srcdatasize: usize,
            psourcename: P2,
            pdefines: Option<*const D3D_SHADER_MACRO>,
            pinclude: P4,
            pentrypoint: P5,
            ptarget: P6,
            flags1: u32,
            flags2: u32,
            ppcode: *mut Option<ID3D10Blob>,
            pperrormsgs: *mut Option<ID3D10Blob>,
        ) -> windows_core::HRESULT
        where
            P2: windows_core::Param<windows_core::PCSTR>,
            P4: windows_core::Param<ID3DInclude>,
            P5: windows_core::Param<windows_core::PCSTR>,
            P6: windows_core::Param<windows_core::PCSTR>,
        {
            windows_core::link!("d3dcompiler_47.dll" "system" fn D3DCompile(psrcdata : *const core::ffi::c_void, srcdatasize : usize, psourcename : windows_core::PCSTR, pdefines : *const D3D_SHADER_MACRO, pinclude : *mut core::ffi::c_void, pentrypoint : windows_core::PCSTR, ptarget : windows_core::PCSTR, flags1 : u32, flags2 : u32, ppcode : *mut *mut core::ffi::c_void, pperrormsgs : *mut *mut core::ffi::c_void) -> windows_core::HRESULT);
            unsafe {
                D3DCompile(
                    psrcdata,
                    srcdatasize,
                    psourcename.param().abi(),
                    pdefines.unwrap_or(core::mem::zeroed()) as _,
                    pinclude.param().abi(),
                    pentrypoint.param().abi(),
                    ptarget.param().abi(),
                    flags1,
                    flags2,
                    core::mem::transmute(ppcode),
                    core::mem::transmute(pperrormsgs),
                )
            }
        }
        #[repr(C)]
        #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
        pub struct D3D_SHADER_MACRO {
            pub Name: windows_core::PCSTR,
            pub Definition: windows_core::PCSTR,
        }
        windows_core::imp::define_interface!(
            ID3D10Blob,
            ID3D10Blob_Vtbl,
            0x8ba5fb08_5195_40e2_ac58_0d989c3a0102
        );
        windows_core::imp::interface_hierarchy!(ID3D10Blob, windows_core::IUnknown);
        impl ID3D10Blob {
            pub unsafe fn GetBufferPointer(&self) -> *mut core::ffi::c_void {
                unsafe {
                    (windows_core::Interface::vtable(self).GetBufferPointer)(
                        windows_core::Interface::as_raw(self),
                    )
                }
            }
            pub unsafe fn GetBufferSize(&self) -> usize {
                unsafe {
                    (windows_core::Interface::vtable(self).GetBufferSize)(
                        windows_core::Interface::as_raw(self),
                    )
                }
            }
        }
        #[repr(C)]
        pub struct ID3D10Blob_Vtbl {
            pub base__: windows_core::IUnknown_Vtbl,
            pub GetBufferPointer:
                unsafe extern "system" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void,
            pub GetBufferSize: unsafe extern "system" fn(*mut core::ffi::c_void) -> usize,
        }
        pub trait ID3D10Blob_Impl: windows_core::IUnknownImpl {
            fn GetBufferPointer(&self) -> *mut core::ffi::c_void;
            fn GetBufferSize(&self) -> usize;
        }
        impl ID3D10Blob_Vtbl {
            pub const fn new<Identity: ID3D10Blob_Impl, const OFFSET: isize>() -> Self {
                unsafe extern "system" fn GetBufferPointer<
                    Identity: ID3D10Blob_Impl,
                    const OFFSET: isize,
                >(
                    this: *mut core::ffi::c_void,
                ) -> *mut core::ffi::c_void {
                    unsafe {
                        let this: &Identity =
                            &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                        ID3D10Blob_Impl::GetBufferPointer(this)
                    }
                }
                unsafe extern "system" fn GetBufferSize<
                    Identity: ID3D10Blob_Impl,
                    const OFFSET: isize,
                >(
                    this: *mut core::ffi::c_void,
                ) -> usize {
                    unsafe {
                        let this: &Identity =
                            &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                        ID3D10Blob_Impl::GetBufferSize(this)
                    }
                }
                Self {
                    base__: windows_core::IUnknown_Vtbl::new::<Identity, OFFSET>(),
                    GetBufferPointer: GetBufferPointer::<Identity, OFFSET>,
                    GetBufferSize: GetBufferSize::<Identity, OFFSET>,
                }
            }
            pub fn matches(iid: &windows_core::GUID) -> bool {
                iid == &<ID3D10Blob as windows_core::Interface>::IID
            }
        }
        impl windows_core::RuntimeName for ID3D10Blob {}
        windows_core::imp::define_interface!(ID3DInclude, ID3DInclude_Vtbl);
        #[repr(C)]
        pub struct ID3DInclude_Vtbl {
            Open: usize,
            Close: usize,
        }
    }
}
